#!/usr/bin/env bash

set -e

# how many CPUs?
if [[ $SLURM_JOB_CPUS_PER_NODE ]]; then
  maxCpus="$SLURM_JOB_CPUS_PER_NODE"
  echo -e "[ $(date): Running with $maxCpus CPUs ]"
else
  maxCpus=1
fi
let "ram_limit = $maxCpus * 3000000000"
echo -e "[ $(date): Allocating $((ram_limit/1000000000)) GB RAM ]"

# cleanup functions
exit_error() {
  echo -e "[ "$(date)": Script aborted ]"
  exit 1
}

# catch exit codes
trap_exit() {
  exitCode=$?
  if (( "exitCode" == 0 )) ; then
    exit 0
  else
    exit_error
  fi
}

# traps
trap exit_error SIGHUP SIGINT SIGTERM
trap trap_exit EXIT

# handle waiting
FAIL=0
fail_wait() {
for job in $(jobs -p); do
  wait $job || let "FAIL+=1"
done
if [[ ! "$FAIL" == 0 ]]; then
  exit 1
fi
}

set -u
