#!/usr/bin/env bash

input_files=""
output_files=""

# parse options
OPTIND=1
IF_N=0
OF_N=0
while getopts ":i:o:" opt; do
    case "$opt" in
        i)  ${input_files[${IF_N}]}="${OPTARG}"
            IF_N=$((IF_N + 1))
            printf "input_files:    %s\n" "${input_files[@]}"
            ;;
        o)  ${output_files[${OF_N}]}="${OPTARG}"
            OF_N=$((OF_N + 1))
            printf "output_files:   %s\n" "${output_files[@]}"
            ;;
        :)
            printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
            exit 1
            ;;
        \?)
            printf "Invalid option: -%s\n" "${OPTARG}" >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"
# non-option arguments start at $1..${n}

source "src/test_header"

if [[ "${#output_files[@]}" -gt 1 ]]; then
    for x in "${output_files[@]}"; do
        cp "${input_files[0]}" "$x"
    done
else
    cp "${input_files[0]}" "${output_files[0]}"
fi

exit 0
