#!/usr/bin/env bash

output_files=""
jgi_login=""
jgi_password=""

# parse options
OPTIND=1
while getopts "o:e:p:" opt; do
    case "$opt" in
        o)  output_files=$OPTARG
            printf "output_files:   %s\n" "$output_files"
            ;;
        e)  jgi_login=$OPTARG
            printf "jgi_login:      %s\n" "$jgi_login"
            ;;
        p)  jgi_password=$OPTARG
            printf "jgi_password:   %s\n" "$jgi_password"
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"
# non-option arguments start at $1..${n}

source "src/test_header"

printf "%s\n" "$output_files" "$jgi_login" "$jgi_password" > "$output_files"
