#!/usr/bin/env bash

output_files=""

# parse options
OPTIND=1
while getopts ":i:o:" opt; do
    case "$opt" in
        o)  output_files="${OPTARG}"
            printf "output_files:   %s\n" "${output_files}"
            ;;
        :)
            printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
            exit 1
            ;;
        \?)
            printf "Invalid option: -%s\n" "${OPTARG}" >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"
# non-option arguments start at $1..${n}

source "src/test_header"

printf "%s" "${output_files}" > "${output_files}"
